"""add_threads_and_thread_messages_tables

Revision ID: aa26b9dc5720
Revises: 9664c0bc639b
Create Date: 2026-04-23 10:18:47.110822

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa26b9dc5720"
down_revision: str | Sequence[str] | None = "9664c0bc639b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_threads_created_at", "threads", ["created_at"], unique=False)
    op.create_index("idx_threads_status", "threads", ["status"], unique=False)
    op.create_index("idx_threads_user_id", "threads", ["user_id"], unique=False)
    op.create_table(
        "thread_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("raw_content", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_thread_messages_created_at", "thread_messages", ["created_at"], unique=False)
    op.create_index("idx_thread_messages_role", "thread_messages", ["role"], unique=False)
    op.create_index("idx_thread_messages_thread_id", "thread_messages", ["thread_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_thread_messages_thread_id", table_name="thread_messages")
    op.drop_index("idx_thread_messages_role", table_name="thread_messages")
    op.drop_index("idx_thread_messages_created_at", table_name="thread_messages")
    op.drop_table("thread_messages")
    op.drop_index("idx_threads_user_id", table_name="threads")
    op.drop_index("idx_threads_status", table_name="threads")
    op.drop_index("idx_threads_created_at", table_name="threads")
    op.drop_table("threads")
    # ### end Alembic commands ###
